### ISSUE TITLE
BukkitPacketEvent may only be triggered synchronously.

### ISSUE THREAD

**Issue by XanderWander** [TlatoaniHJ/ThatPacketAddon#1]
https://pastebin.com/1pQyAQ0r - Error
https://pastebin.com/WqxNffbZ - Versions
https://pastebin.com/kZdwqbt1 - Code

Is this an issue with Paper?

**Comment by EhhXD** [comment]
Tried using normal spigot and am getting the same errors on 1.14.4.

**Comment by TheBentoBox** [comment]
Can confirm, doesn't seem super usable on 1.14.

**Comment by TlatoaniHJ** [comment]
Fixed in ThatPacketAddon 1.0-BETA.3.

**Comment by Ehhthan** [comment]
Bug fix works for me on Paper 1.14.4
