### ISSUE TITLE
Conflict with Skript 2.5.2 (Console Errors)

### ISSUE THREAD

**Issue by annemettean** [TlatoaniHJ/ThatPacketAddon#7]
I have installed ThatPacketAddon on my Minecraft server, but the plugin will be disabled due to some console errors. This happens after I have updated the skript plugin version and the server jar from spigot 1.12.2 to paperspigot 1.12.2

Server Version:
Paperspigot 1.12.2

Skript Version:
2.5.2

ThatPacketAddon Version:
1.0 BETA 3

Console Error:
https://pastebin.com/TikHeU6g

**Comment by JohnathanEberly** [comment]
Can confirm on PaperSpigot 1.16.4. Interestingly, it works on Skript 2.5.1.

**Comment by annemettean** [comment]
Interesting, maybe it could be a problem on older versions of paper spigot. Will just try to do some more testing to see if that could be it.

**Comment by annemettean** [comment]
It seems that ThatPakcetAddon does not support the latest version of skript (2.5.2). Every time I test it with skript version 2.5.1 it works, but when I test it with skript version 2.5.2 then it does not work.

**Comment by JohnathanEberly** [comment]
ShaneBee posted a version of Skript on the Discord a few days ago that fixes it, so I think it's an issue with Skript and not ThatPacketAddon, and should be fixed in the next release.

**Comment by annemettean** [comment]
I think you are right, I will close this issue for now.
